### ISSUE TITLE
Cargo.lock file

### ISSUE THREAD

**Issue by newAM** [psurply/dwfv#11]
I really like this project, thank you for creating it!

I would like to package this for [NixOS](https://github.com/NixOS/nixpkgs), but nix requires reproducible builds, and as part of that a `Cargo.lock` file is needed.  Typically this file is included for binaries, but not for libraries (source: [Cargo FAQ](https://doc.rust-lang.org/cargo/faq.html#why-do-binaries-have-cargolock-in-version-control-but-not-libraries)).

I know that not everyone likes committing a `Cargo.lock` file; would you be willing to commit the `Cargo.lock` file to make this easier to package?

**Comment by psurply** [comment]
> would you be willing to commit the Cargo.lock file to make this easier to package?

Sure: I just added a Cargo.lock file to the repo. Thanks for the report!

**Comment by newAM** [comment]
Thank you!
