### ISSUE TITLE
Search expressions; documentation and implementation

### ISSUE THREAD

**Issue by parasyte** [psurply/dwfv#3]
Hi!

I've been playing around with this little app, and I think it's a pretty solid waveform viewer and editor. I do have some questions relating to the search expressions, though. Particularly, it would be nice to document the syntax (or link to external documentation, if this is an implementation of a common syntax that I'm just unaware of?)

The second question is about the implementation details... One of the things I love about Rust is the level of control it gives. And I can't help but notice that the expression grammar is very small, but the parser infrastructure is disproportionately heavy. The build time is really hurt (IMHO) by including all of `lalrpop` for what looks like a very simple expression AST.

There are also a couple of annoying issues with `lalrpop`; the visibility modifier issue linked in #2, for example. And 70-or-so warnings emitted by `cargo clippy` are directly related to the code generated by `lalrpop`. Would you be opposed to replacing the parser with something like [`nom`](https://crates.io/crates/nom)? This is a very light weight parser generator crate with only a single required dependency. `nom` does have some problems of its own, but I don't think it will be any trouble with this simplistic expression grammar.

If you would like, I could contribute a new parser. But I'm still interested in the expression syntax docs, and it would really help when working on such a rewrite!

**Comment by psurply** [comment]
Hello,

The syntax of the search expressions is completely custom and isn't based on an existing standard. I can write some proper documentation about it when I find some time and I am fine with changing/improving the syntax if necessary.

I am also willing to replace `LALRPOP` with something more lightweight and, at first glance, I agree that `nom` seems to be a reasonable alternative. A pull request for updating the parser would be indeed very welcome.

Thanks!
